INSERT INTO STG.LdMigrTblHsh
(
	ClientCd,
	TblId,
	ColId,
	IsStrictMatch,
	DataType,
	DefaultValue,
	ColDescription,
	HashAlgorithm,
	HashTblId,
	HashColId,
	ColName,
	IsNullable,
	SrcTblId,
	SrcColId,
	ColTransform,
	RowCreatedTs,
	RowCreatedBy
)
SELECT 
	Hsh.ClientCd,
	Hsh.TblId,
	Hsh.ColId,
	Hsh.IsStrictMatch,
	Hsh.DataType,
	Hsh.DefaultValue,
	Hsh.ColDescription,
	Hsh.HashAlgorithm,
	Hsh.HashTblId,
	Hsh.HashColId,
	Hsh.ColName,
	Hsh.IsNullable,
	Hsh.SrcTblId,
	Hsh.SrcColId,
	Hsh.ColTransform,
	Hsh.RowCreatedTs,
	Hsh.RowCreatedBy
FROM DE_1000_00.WSCL.WrkVwClMigrTblHsh Hsh
;