CREATE OR ALTER VIEW #WsToClRepoSchema.WrkVwClMigrTblHsh
(
	ClientCd,
	TblName,
	TblId,
	ColId,
	IsStrictMatch,
	DataType,
	DefaultValue,
	ColDescription,
	HashAlgorithm,
	HashTblId,
	HashColId,
	ColName,
	IsNullable,
	SrcTblId,
	SrcColId,	
	ColTransform,
	RowCreatedTs,
	RowCreatedBy
) AS
SELECT
	'#ClientCode',
	TblName,
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),29,4)),
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),29,4)),
	'true',
	DataType,
	COALESCE(DefaultValue,''),
	COALESCE(ColDescription,''),
	'MD5',
	CASE
		WHEN LEN(TRIM(SrcTblName)) > 1
		THEN LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),1,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),5,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),9,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),13,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),17,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),21,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),25,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),29,4))
		ELSE '0'
	END,
	CASE
		WHEN LEN(TRIM(SrcColName)) > 1
		THEN LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),1,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),5,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),9,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),13,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),17,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),21,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),25,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),29,4))
		ELSE '0'
	END,		
	ColName,
	Nullable,
	'0',
	'0',
	'',
	GETDATE(),
	'DEA-PS-WS-Repo-To-CL-Repo.psm1'
FROM #WsToClRepoSchema.WrkVwClMigrTblHsh05
WHERE ColKeyType IS NULL
;