CREATE OR ALTER VIEW #WsToClRepoSchema.WrkVwClMigrTblDtl
(
	ClientCd,
	TblName,
	TblId,
	ColId,
	IsIncremental,
	IsStrictMatch,
	DataType,
	DefaultValue,
	ColDescription,
	ColName,
	IsNullable,
	IsPrimaryKey,
	IsUniqueKey,
	SrcTblId,
	SrcColId,	
	ColTransform,
	TblType,
	ColOrder,
	IsBusinessKey,
	IsChangeDetection,
	RowCreatedTs,
	RowCreatedBy
) AS
-- NON SOURCE MAPPING OBJECTS (EXCLUDE - LOAD, RETRO & VIEW)
SELECT
	'#ClientCode',
	TblName,	
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),29,4)),
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),29,4)),
	IsIncremental,
	'false',
	DataType,
	COALESCE(DefaultValue,''),
	COALESCE(ColDescription,''),
	ColName,
	Nullable,
	PrimaryKey,
	UniqueKey,	
	CASE
		WHEN LEN(TRIM(SrcTblName)) > 1 AND (LEN(TRIM(CONVERT(VARCHAR,ColTransform))) = 0 OR ColTransform IS NULL) AND (TblName <> SrcTblName)
		THEN LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),1,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),5,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),9,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),13,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),17,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),21,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),25,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),29,4))
		ELSE '0'
	END,
	CASE
		WHEN LEN(TRIM(SrcTblName)) > 1 AND (LEN(TRIM(CONVERT(VARCHAR,ColTransform))) = 0 OR ColTransform IS NULL) AND (TblName <> SrcTblName)
		THEN LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),1,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),5,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),9,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),13,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),17,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),21,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),25,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),29,4))
		ELSE '0'
	END,	
	COALESCE(ColTransform,''),
	WsWrkDtl.TblType,
	WsWrkDtl.ColOrder,
	WsWrkDtl.IsBusinessKey,
	WsWrkDtl.IsChangeDetection,	
	GETDATE(),
	'DEA-PS-WS-Repo-To-CL-Repo.psm1'
FROM #WsToClRepoSchema.WrkVwClMigrTblDtl05 WsWrkDtl
WHERE WsWrkDtl.TblType NOT IN ('Load Table','SOURCE','View') 
  AND WsWrkDtl.ColType IS NULL
UNION ALL
-- NON SOURCE MAPPING OBJECTS (VIEW)
SELECT
	'#ClientCode',
	TblName,
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),29,4)),
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),29,4)),
	IsIncremental,
	'false',
	DataType,
	COALESCE(DefaultValue,''),
	COALESCE(ColDescription,''),
	ColName,
	Nullable,
	PrimaryKey,
	UniqueKey,	
	CASE
		WHEN LEN(TRIM(SrcTblName)) > 1 AND (LEN(TRIM(CONVERT(VARCHAR,ColTransform))) = 0 OR ColTransform IS NULL) AND (TblName <> SrcTblName)
		THEN LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),1,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),5,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),9,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),13,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),17,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),21,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),25,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),29,4))
		ELSE '0'
	END,
	CASE
		WHEN LEN(TRIM(SrcTblName)) > 1 AND (LEN(TRIM(CONVERT(VARCHAR,ColTransform))) = 0 OR ColTransform IS NULL) AND (TblName <> SrcTblName)
		THEN LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),1,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),5,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),9,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),13,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),17,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),21,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),25,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),29,4))
		ELSE '0'
	END,	
	COALESCE(ColTransform,''),
	WsWrkDtl.TblType,
	WsWrkDtl.ColOrder,
	WsWrkDtl.IsBusinessKey,
	WsWrkDtl.IsChangeDetection,		
	GETDATE(),
	'DEA-PS-WS-Repo-To-CL-Repo.psm1'
FROM #WsToClRepoSchema.WrkVwClMigrTblDtl05 WsWrkDtl
WHERE WsWrkDtl.TblType IN ('View')
  AND WsWrkDtl.ColType IS NULL
UNION ALL
-- NON SOURCE MAPPING OBJECTS (LOAD & RETRO)
SELECT
	'#ClientCode',
	TblName,
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),29,4)),
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),29,4)),
	IsIncremental,
	'true',
	DataType,
	COALESCE(DefaultValue,''),
	COALESCE(ColDescription,''),
	ColName,
	Nullable,
	PrimaryKey,
	UniqueKey,	
	'0',
	'0',	
	COALESCE(ColTransform,''),
	'Source',
	WsWrkDtl.ColOrder,
	WsWrkDtl.IsBusinessKey,
	WsWrkDtl.IsChangeDetection,		
	GETDATE(),
	'DEA-PS-WS-Repo-To-CL-Repo.psm1'
FROM #WsToClRepoSchema.WrkVwClMigrTblDtl05 WsWrkDtl
WHERE WsWrkDtl.TblType IN ('Load Table','SOURCE')
  AND WsWrkDtl.ColType IS NULL
UNION ALL
-- SOURCE MAPPING OBJECTS
SELECT
	'#ClientCode',
	TblName,
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),29,4)),
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),29,4)),
	IsIncremental,
	'false',
	DataType,
	COALESCE(DefaultValue,''),
	COALESCE(ColDescription,''),
	ColName,
	Nullable,
	PrimaryKey,
	UniqueKey,	
	CASE
		WHEN LEN(TRIM(SrcTblName)) > 1 AND (LEN(TRIM(CONVERT(VARCHAR,ColTransform))) = 0 OR ColTransform IS NULL) AND (TblName <> SrcTblName)
		THEN LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),1,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),5,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),9,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),13,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),17,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),21,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),25,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcTblName),2),29,4))
		ELSE '0'
	END,
	CASE
		WHEN LEN(TRIM(SrcTblName)) > 1 AND (LEN(TRIM(CONVERT(VARCHAR,ColTransform))) = 0 OR ColTransform IS NULL) AND (TblName <> SrcTblName)
		THEN LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),1,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),5,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),9,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),13,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),17,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),21,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),25,4)) + '-' +
			 LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',SrcColName),2),29,4))
		ELSE '0'
	END,	
	COALESCE(ColTransform,''),
	WsWrkDtl.TblType,
	WsWrkDtl.ColOrder,
	WsWrkDtl.IsBusinessKey,
	WsWrkDtl.IsChangeDetection,		
	GETDATE(),
	'DEA-PS-WS-Repo-To-CL-Repo.psm1'
FROM #WsToClRepoSchema.WrkVwClMigrTblDtl10 WsWrkDtl
WHERE WsWrkDtl.ColType IS NULL
;