CREATE OR ALTER VIEW #WsToClRepoSchema.WrkVwClMigrTblAud
(
	ClientCd,
	TblName,
	TblId,
	ColId,
	IsStrictMatch,
	DataType,
	DefaultValue,
	ColDescription,
	HashColumns,
	ColName,
	IsNullable,
	SrcTblId,
	SrcColId,	
	ColType,
	ColTransform,
	RowCreatedTs,
	RowCreatedBy
) AS
-- NON SOURCE MAPPING OBJECTS
SELECT
	'#ClientCode',
	TblName,
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),29,4)),
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),29,4)),
	'true',
	DataType,
	COALESCE(DefaultValue,''),
	COALESCE(ColDescription,''),
	'[]',
	ColName,
	Nullable,
	'0',
	'0',
	ColType,
	CASE 
		WHEN ColType IN ('Start Date', 'Created Date', 'Updated Date')
		THEN 'CAST(CURRENT_TIMESTAMP AS TIMESTAMP)'
		WHEN ColType = 'Version'
		THEN '1'
		WHEN ColType = 'Current Flag'
		THEN 'Y'
		WHEN ColType = 'End Date'
		THEN 'CAST(''2999-12-31 00:00:00'' AS TIMESTAMP)'
		ELSE ''
	END,
	GETDATE(),
	'DEA-PS-WS-Repo-To-CL-Repo.psm1'
FROM #WsToClRepoSchema.WrkVwClMigrTblAud05
UNION ALL
-- SOURCE MAPPING OBJECTS
SELECT
	'#ClientCode',
	TblName,
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',TblName),2),29,4)),
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),1,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),5,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),9,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),13,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),17,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),21,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),25,4)) + '-' +
	LOWER(SUBSTRING(CONVERT(VARCHAR(100),HASHBYTES('MD5',ColName),2),29,4)),
	'true',
	DataType,
	COALESCE(DefaultValue,''),
	COALESCE(ColDescription,''),
	'[]',
	ColName,
	Nullable,
	'0',
	'0',
	ColType,
	CASE 
		WHEN ColType IN ('Start Date', 'Created Date', 'Updated Date')
		THEN 'CAST(CURRENT_TIMESTAMP AS TIMESTAMP)'
		WHEN ColType = 'Version'
		THEN '1'
		WHEN ColType = 'Current Flag'
		THEN 'Y'
		WHEN ColType = 'End Date'
		THEN 'CAST(''2999-12-31 00:00:00'' AS TIMESTAMP)'
		ELSE ''
	END,
	GETDATE(),
	'DEA-PS-WS-Repo-To-CL-Repo.psm1'
FROM #WsToClRepoSchema.WrkVwClMigrTblAud10
;